openapi: 3.0.0
info:
  title: FuelSync Hub API
  version: "1.0.0"
servers:
  - url: /v1
paths:
  /admin/users:
    post:
      summary: Create super admin user
    get:
      summary: List super admin users
  /v1/auth/login:
    post:
      summary: User login and JWT issuance
  /v1/users:
    post:
      summary: Create tenant user
    get:
      summary: List tenant users
  /v1/stations:
    post:
      summary: Create station
    get:
      summary: List stations
  /v1/stations/{id}:
    put:
      summary: Update station
    delete:
      summary: Delete station
  /v1/pumps:
    post:
      summary: Create pump
    get:
      summary: List pumps
  /v1/pumps/{id}:
    delete:
      summary: Delete pump
  /v1/nozzles:
    post:
      summary: Create nozzle
    get:
      summary: List nozzles
  /v1/nozzles/{id}:
    delete:
      summary: Delete nozzle
  /v1/nozzle-readings:
    post:
      summary: Record nozzle reading and generate sale
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nozzleId:
                  type: string
                reading:
                  type: number
                recordedAt:
                  type: string
                  format: date-time
                creditorId:
                  type: string
                  nullable: true
                paymentMethod:
                  type: string
                  enum: [cash, card, upi, credit]
                  description: |
                    Optional. Currently the API infers 'cash' or 'credit' based on
                    `creditorId`. Support for `card` and `upi` is planned.
              required:
                - nozzleId
                - reading
                - recordedAt
    get:
      summary: List nozzle readings
  /v1/fuel-prices:
    post:
      summary: Create fuel price entry
    get:
      summary: List fuel prices
  /v1/creditors:
    post:
      summary: Create creditor
    get:
      summary: List creditors
  /v1/creditors/{id}:
    put:
      summary: Update creditor
    delete:
      summary: Delete creditor
  /v1/credit-payments:
    post:
      summary: Record credit payment
    get:
      summary: List credit payments
  /v1/fuel-deliveries:
    post:
      summary: Record fuel delivery
    get:
      summary: List fuel deliveries
  /v1/reconciliation:
    post:
      summary: Run daily reconciliation
  /v1/reconciliation/{stationId}:
    get:
      summary: Get reconciliation summary
  /admin/tenants/summary:
    get:
      summary: Get tenant metrics summary
  /admin/tenants:
    get:
      summary: List tenants
    post:
      summary: Create tenant
  /v1/tenants:
    get:
      summary: List tenants
    post:
      summary: Create tenant

# TODO: Define component schemas for all routes
