name: Build & Deploy Node.js app to Azure Web App - fuelsync

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install packages, generate Prisma & build project
        run: |
          npm ci
          npm run build
      - name: Test (unit + integration)
        run: npm run test:unit
      - name: Prepare artifact
        run: |
          zip -r release.zip . -x '.git*' 'node_modules/*'
      - uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app
      - run: unzip release.zip
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: fuelsync
          slot-name: 'Production'
          package: .
