name: Build and deploy Node.js app to Azure Web App - fuelsync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and prisma generate
        run: |
          npm install
          chmod +x node_modules/.bin/prisma || true
          npx prisma generate
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment (include node_modules)
        run: zip -r release.zip . -x ".git/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F3F917245D074FC0968D03A8C630A7FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DB48808926EC4B3F9ABDC4D448D6813F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_67F9681C1A8546E2BCEA9DAF3D93904B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fuelsync'
          slot-name: 'Production'
          package: .
